services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  web:
    build: .
    environment:
      - ENVIRONMENT=DEV
      - HOST=localhost
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - '8000:8000'
    depends_on:
      - redis